/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PitchRouteImport } from './routes/pitch'
import { Route as DetailRouteImport } from './routes/_detail'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVaultRouteImport } from './routes/_app/vault'
import { Route as AppPortfolioRouteImport } from './routes/_app/portfolio'
import { Route as AppPointsRouteImport } from './routes/_app/points'
import { Route as AppMarketsRouteImport } from './routes/_app/markets'
import { Route as AppLeaderboardRouteImport } from './routes/_app/leaderboard'
import { Route as AppJarvisRouteImport } from './routes/_app/jarvis'
import { Route as AppGuideRouteImport } from './routes/_app/guide'
import { Route as DetailPredictionsOracleIdRouteImport } from './routes/_detail/predictions/$oracleId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchRoute = PitchRouteImport.update({
  id: '/pitch',
  path: '/pitch',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailRoute = DetailRouteImport.update({
  id: '/_detail',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVaultRoute = AppVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppPointsRoute = AppPointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketsRoute = AppMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppJarvisRoute = AppJarvisRouteImport.update({
  id: '/jarvis',
  path: '/jarvis',
  getParentRoute: () => AppRoute,
} as any)
const AppGuideRoute = AppGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AppRoute,
} as any)
const DetailPredictionsOracleIdRoute =
  DetailPredictionsOracleIdRouteImport.update({
    id: '/predictions/$oracleId',
    path: '/predictions/$oracleId',
    getParentRoute: () => DetailRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pitch': typeof PitchRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/guide': typeof AppGuideRoute
  '/jarvis': typeof AppJarvisRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/markets': typeof AppMarketsRoute
  '/points': typeof AppPointsRoute
  '/portfolio': typeof AppPortfolioRoute
  '/vault': typeof AppVaultRoute
  '/predictions/$oracleId': typeof DetailPredictionsOracleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pitch': typeof PitchRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/guide': typeof AppGuideRoute
  '/jarvis': typeof AppJarvisRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/markets': typeof AppMarketsRoute
  '/points': typeof AppPointsRoute
  '/portfolio': typeof AppPortfolioRoute
  '/vault': typeof AppVaultRoute
  '/predictions/$oracleId': typeof DetailPredictionsOracleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_detail': typeof DetailRouteWithChildren
  '/pitch': typeof PitchRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_app/guide': typeof AppGuideRoute
  '/_app/jarvis': typeof AppJarvisRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/markets': typeof AppMarketsRoute
  '/_app/points': typeof AppPointsRoute
  '/_app/portfolio': typeof AppPortfolioRoute
  '/_app/vault': typeof AppVaultRoute
  '/_detail/predictions/$oracleId': typeof DetailPredictionsOracleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pitch'
    | '/privacy'
    | '/terms'
    | '/guide'
    | '/jarvis'
    | '/leaderboard'
    | '/markets'
    | '/points'
    | '/portfolio'
    | '/vault'
    | '/predictions/$oracleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pitch'
    | '/privacy'
    | '/terms'
    | '/guide'
    | '/jarvis'
    | '/leaderboard'
    | '/markets'
    | '/points'
    | '/portfolio'
    | '/vault'
    | '/predictions/$oracleId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_detail'
    | '/pitch'
    | '/privacy'
    | '/terms'
    | '/_app/guide'
    | '/_app/jarvis'
    | '/_app/leaderboard'
    | '/_app/markets'
    | '/_app/points'
    | '/_app/portfolio'
    | '/_app/vault'
    | '/_detail/predictions/$oracleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DetailRoute: typeof DetailRouteWithChildren
  PitchRoute: typeof PitchRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch': {
      id: '/pitch'
      path: '/pitch'
      fullPath: '/pitch'
      preLoaderRoute: typeof PitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_detail': {
      id: '/_detail'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vault': {
      id: '/_app/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AppVaultRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolio': {
      id: '/_app/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/points': {
      id: '/_app/points'
      path: '/points'
      fullPath: '/points'
      preLoaderRoute: typeof AppPointsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/markets': {
      id: '/_app/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof AppMarketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jarvis': {
      id: '/_app/jarvis'
      path: '/jarvis'
      fullPath: '/jarvis'
      preLoaderRoute: typeof AppJarvisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guide': {
      id: '/_app/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof AppGuideRouteImport
      parentRoute: typeof AppRoute
    }
    '/_detail/predictions/$oracleId': {
      id: '/_detail/predictions/$oracleId'
      path: '/predictions/$oracleId'
      fullPath: '/predictions/$oracleId'
      preLoaderRoute: typeof DetailPredictionsOracleIdRouteImport
      parentRoute: typeof DetailRoute
    }
  }
}

interface AppRouteChildren {
  AppGuideRoute: typeof AppGuideRoute
  AppJarvisRoute: typeof AppJarvisRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppMarketsRoute: typeof AppMarketsRoute
  AppPointsRoute: typeof AppPointsRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppVaultRoute: typeof AppVaultRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppGuideRoute: AppGuideRoute,
  AppJarvisRoute: AppJarvisRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppMarketsRoute: AppMarketsRoute,
  AppPointsRoute: AppPointsRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppVaultRoute: AppVaultRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DetailRouteChildren {
  DetailPredictionsOracleIdRoute: typeof DetailPredictionsOracleIdRoute
}

const DetailRouteChildren: DetailRouteChildren = {
  DetailPredictionsOracleIdRoute: DetailPredictionsOracleIdRoute,
}

const DetailRouteWithChildren =
  DetailRoute._addFileChildren(DetailRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DetailRoute: DetailRouteWithChildren,
  PitchRoute: PitchRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
